version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env
    volumes:
      - ./auth-service/node_modules:/app/node_modules  # Persistir node_modules
      - ./auth-service:/app  # Persistir el código fuente
    environment:
      - DB_HOST=your-auth-service-rds-endpoint.amazonaws.com
      - DB_PORT=5432
      - DB_USER=alexis
      - DB_PASSWORD=your_password
      - DB_NAME=your_auth_database_name

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    env_file:
      - ./user-service/.env
    volumes:
      - ./user-service/node_modules:/app/node_modules  # Persistir node_modules
      - ./user-service:/app  # Persistir el código fuente
    environment:
      - DB_HOST=your-user-service-rds-endpoint.amazonaws.com
      - DB_PORT=5432
      - DB_USER=alexis
      - DB_PASSWORD=your_password
      - DB_NAME=your_user_database_name

  recipe-service:
    build: ./recipe-service
    ports:
      - "4002:4002"
    env_file:
      - ./recipe-service/.env
    volumes:
      - ./recipe-service/node_modules:/app/node_modules  # Persistir node_modules
      - ./recipe-service:/app  # Persistir el código fuente
    environment:
      - MONGO_HOST=your-ec2-ip-address
      - MONGO_PORT=27017
      - MONGO_DB=recipe_database_name

  comment-service:
    build: ./comment-service
    ports:
      - "4003:4003"
    env_file:
      - ./comment-service/.env
    volumes:
      - ./comment-service/node_modules:/app/node_modules  # Persistir node_modules
      - ./comment-service:/app  # Persistir el código fuente
    environment:
      - MONGO_HOST=your-ec2-ip-address
      - MONGO_PORT=27017
      - MONGO_DB=comment_database_name

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    env_file:
      - ./gateway-service/.env
    volumes:
      - ./gateway-service/node_modules:/app/node_modules  # Persistir node_modules
      - ./gateway-service:/app  # Persistir el código fuente

# Volúmenes persistentes
volumes:
  pgdata:  # Volumen para la base de datos PostgreSQL
