version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env
    environment:
      - DB_HOST=${DB_HOST_AUTH}
      - DB_PORT=${DB_PORT_AUTH}
      - DB_USER=${DB_USER_AUTH}
      - DB_PASSWORD=${DB_PASSWORD_AUTH}
      - DB_NAME=${DB_NAME_AUTH}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT_AUTH}

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    env_file:
      - ./user-service/.env
    environment:
      - DB_HOST=${DB_HOST_USER}
      - DB_PORT=${DB_PORT_USER}
      - DB_USER=${DB_USER_USER}
      - DB_PASSWORD=${DB_PASSWORD_USER}
      - DB_NAME=${DB_NAME_USER}
      - PORT=${PORT_USER}

  comment-service:
    build: ./comment-service
    ports:
      - "4002:4002"
    env_file:
      - ./comment-service/.env
    environment:
      - DB_HOST=${DB_HOST_COMMENT}
      - DB_PORT=${DB_PORT_COMMENT}
      - DB_USER=${DB_USER_COMMENT}
      - DB_PASSWORD=${DB_PASSWORD_COMMENT}
      - DB_NAME=${DB_NAME_COMMENT}
      - PORT=${PORT_COMMENT}

  gateway-service:
    build: ./gateway-service
    ports:
      - "4003:4003"
    env_file:
      - ./gateway-service/.env
    environment:
      - DB_HOST=${DB_HOST_GATEWAY}
      - DB_PORT=${DB_PORT_GATEWAY}
      - DB_USER=${DB_USER_GATEWAY}
      - DB_PASSWORD=${DB_PASSWORD_GATEWAY}
      - DB_NAME=${DB_NAME_GATEWAY}
      - PORT=${PORT_GATEWAY}

  recipe-service:
    build: ./recipe-service
    ports:
      - "4004:4004"
    env_file:
      - ./recipe-service/.env
    environment:
      - DB_HOST=${DB_HOST_RECIPE}
      - DB_PORT=${DB_PORT_RECIPE}
      - DB_USER=${DB_USER_RECIPE}
      - DB_PASSWORD=${DB_PASSWORD_RECIPE}
      - DB_NAME=${DB_NAME_RECIPE}
      - PORT=${PORT_RECIPE}
