services:
  auth-service:
    image: yourusername/auth-service:latest
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=auth.ci8p78npdh7f.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_USER=alexis
      - DB_PASSWORD=admin123
      - DB_NAME=postgres

  user-service:
    image: alexismendozaa/user-service:latest
    ports:
      - "4001:4001"
    environment:
      - DB_HOST=user.ci8p78npdh7f.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_USER=alexis
      - DB_PASSWORD=admin123
      - DB_NAME=postgres

  recipe-service:
    image: alexismendozaa/recipe-service:latest
    ports:
      - "4002:4002"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=recipedb

  comment-service:
    image: alexismendozaa/comment-service:latest
    ports:
      - "4003:4003"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=commentdb

  gateway-service:
    image: alexismendozaa/gateway-service:latest
    ports:
      - "8080:8080"
