version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env
    volumes:
      - ./auth-service/node_modules:/app/node_modules  # Persistir node_modules
      - ./auth-service:/app  # Persistir el código fuente
    environment:
      - DB_HOST=${DB_HOST_AUTH}
      - DB_PORT=${DB_PORT_AUTH}
      - DB_USER=${DB_USER_AUTH}
      - DB_PASSWORD=${DB_PASSWORD_AUTH}
      - DB_NAME=${DB_NAME_AUTH}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT_AUTH}

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    env_file:
      - ./user-service/.env
    volumes:
      - ./user-service/node_modules:/app/node_modules  # Persistir node_modules
      - ./user-service:/app  # Persistir el código fuente
    environment:
      - DB_HOST=${DB_HOST_USER}
      - DB_PORT=${DB_PORT_USER}
      - DB_USER=${DB_USER_USER}
      - DB_PASSWORD=${DB_PASSWORD_USER}
      - DB_NAME=${DB_NAME_USER}
      - PORT=${PORT_USER}

  comment-service:
    build: ./comment-service
    ports:
      - "4002:4002"
    env_file:
      - ./comment-service/.env
    volumes:
      - ./comment-service/node_modules:/app/node_modules  # Persistir node_modules
      - ./comment-service:/app  # Persistir el código fuente
    environment:
      - MONGO_URI=mongodb://mongo:27017/commentdb  # Conexión a MongoDB
      - PORT=${PORT_COMMENT}
    depends_on:
      - mongo  # El contenedor de comment-service depende de mongo

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    env_file:
      - ./gateway-service/.env
    volumes:
      - ./gateway-service/node_modules:/app/node_modules  # Persistir node_modules
      - ./gateway-service:/app  # Persistir el código fuente
    environment:
      - PORT=${PORT_GATEWAY}

  recipe-service:
    build: ./recipe-service
    ports:
      - "4003:4003"
    env_file:
      - ./recipe-service/.env
    volumes:
      - ./recipe-service/node_modules:/app/node_modules  # Persistir node_modules
      - ./recipe-service:/app  # Persistir el código fuente
    environment:
      - MONGO_URI=mongodb://mongo:27017/recipedb  # Conexión a MongoDB
      - PORT=${PORT_RECIPE}
    depends_on:
      - mongo  # El contenedor de recipe-service depende de mongo

  mongo:
    image: mongo:latest  # Usando la imagen oficial de MongoDB
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"  # Exponiendo el puerto 27017 de MongoDB
    volumes:
      - mongo-data:/data/db  # Volumen para persistir los datos de MongoDB

volumes:
  mongo-data:  # Volumen persistente para los datos de MongoDB
